//
// CountDownView.h
// Generated by Core Animator version 1.0 on 3/15/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface CountDownView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

// CountDown
- (void)addCountDownAnimation;
- (void)addCountDownAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addCountDownAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addCountDownAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addCountDownAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeCountDownAnimation;

- (void)removeAllAnimations;

@end